language: node_js
sudo: required
services:
    - docker
before_install:
    - docker build -t lemore/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true lemore/docker-react npm run test